name: Deploy Docker image to Azure Windows VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t karizma .

      - name: Save Docker image to TAR file
        run: |
         docker save -o karizma.tar karizma
      - name: Transfer to Windows VM
        run: |
         scp -r \karizma.tar ${{ secrets.WINDOWS_VM_USERNAME }}@:${{ secrets.WINDOWS_VM_HOST }}/C:\Users\haseeb\Desktop

      - name: Execute commands on Azure Windows VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WINDOWS_VM_HOST }}
          username: ${{ secrets.WINDOWS_VM_USERNAME }}
          password: ${{ secrets.WINDOWS_VM_PASSWORD }}
          port: ${{ secrets.WINDOWS_VM_SSH_PORT }}
          script: |
            cd C:/Users/haseeb/Desktop
            docker load -i karizma.tar
            docker run -d -p 8080:80 karizma
