name: Deploy Docker image to Azure Windows VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build Docker image
        run: |
          docker build -t karizma .
          docker save -o karizma.tar karizma

      - name: Transfer Docker image to Azure Windows VM
        run: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null karizma.tar ${{ secrets.WINDOWS_VM_USERNAME }}@${{ secrets.WINDOWS_VM_HOST }}:'C:\Users\haseeb\Desktop\'

      - name: Execute commands on Azure Windows VM
        run: |
          sshpass -p ${{ secrets.WINDOWS_VM_PASSWORD }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.WINDOWS_VM_USERNAME }}@${{ secrets.WINDOWS_VM_HOST }} 'cd C:\Users\haseeb\Desktop; docker load -i karizma.tar; docker run -d -p 8080:80 karizma'
